[package]
name = "baserow-rs"
description = "A Rust client for the Baserow API."
version = "0.1.3"
edition = "2021"
categories = ["database"]
license = "Apache-2.0"
repository = "https://github.com/cedricziel/baserow-rs"
issues = "https://github.com/cedricziel/baserow-rs/issues"

[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
